package channelAdm;

public enum ChannelMarker {

	AUTO_GENERATED ("--TSXFLAG_AutoGeneratedChannel");
	
	final String value;
	
	private ChannelMarker (String marker) {
		value = marker;
	}
	
	public String getValue () {
		return value;
	}
}
